---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170701090350"
editor:
  name: "StarterAdditionEditor"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.2"
  parameters:
    - "group": "org.springframework.boot"
    - "artifact": "spring-boot-starter-security"

